### ISSUE TITLE
The crontab command only creates a new wallpaper, does not set it as the wallpaper.

### ISSUE THREAD

**Issue by shardul08** [anirudhajith/process-wallpaper#22]
The crontab executes the updateWallpaper script which only runs generateWallpaper which creates a new wallpaper. It is needed to run the setWallpaper script from updateWallpaper script after creating the new wallpaper.  I have opened a pull request #17 with the required changes. Please review it.

**Comment by anirudhajith** [comment]
If `setup.sh` is run in the first time the user clones the repo, the wallpaper will be set to `wallpaper.png` since both `updateWallpaper.sh` and `setWallpaper.sh` are run. After that, unless the user manually changes their wallpaper to something else, any changes to `wallpaper.png` will reflect automatically on the desktop. That's the behavior I'm seeing on Ubuntu.
Is an additional call to `setWallpaper.sh` proving necessary on your system? If so, we can add the required call to `setWallpaper.sh`.

**Comment by shardul08** [comment]
I am sorry I didn't know how `gsettings` work. Just read about it and realized it automatically sets `wallpaper.png` as the wallpaper whenever there is any change in it. I thought we had to manually call `setWallpaper.sh` every time there is a change in `wallpaper.png`. Just tested in my system and it works fine. I will close PR #17.
